package com.example.navigation.flowEngine.steps.enums

enum class PaymentMethodId {
    DEBVISA, DEBELO, MASTER, DEBMASTER, VISA, MAESTRO, ELO, HIPERCARD, DEBCABAL, NARANJA, AMEX, CABAL, CORDOBESA, MERCADOPAGO_CC, SIVALE_DESPENSA, CMR, NATIVA, SIVALE_RESTAURANT, CORDIAL, DINERS, SODEXO_FOOD, ARGENCARD, CENCOSUD, SODEXO_GIFT, SODEXO_PREMIUM, SODEXO_GROCERY
}